[build]
  base = "/"
  publish = "/out"
  functions = "/functions"
  command = "yarn build"

# Client Side Routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  # force = true

# Clean up netlify functions paths
[[ redirects ]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[dev]
  command = "yarn bundle"
  framework = "#custom"
  targetPort = 3001
  port = 3000
  autoLaunch = false
