[build]
  base = "/"
  publish = "/out"
  functions = "/functions"
  command = "yarn build"

[[ redirects ]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[dev]
  command = "yarn bundle"
  framework = "#custom"
  targetPort = 3001
  port = 3000
  autoLaunch = false
