name: GistMarks CI

on:
  pull_request:
    types: [opened, synchronize, closed]
    branches: ["master"]

jobs:
  lint-and-test-app:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-versions: [12.x]

    steps:
      # Setup - Checkout Code
      - uses: actions/checkout@v2

      # Setup - Configure NodeJS
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
        env:
          CI: true

      # Step 1 - Yarn
      - name: Install Yarn
        run: sudo npm install -g yarn
        env:
          CI: true

      # Step 2 - Install Dependencies
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
        env:
          CI: true

      # Step 3 - Typechecking
      - name: Typescript
        run: yarn tsc
        env:
          CI: true

      # Step 4 - Prettier
      - name: Prettier
        run: yarn format
        env:
          CI: true

      # Step 5 - Linting
      - name: Lint
        run: yarn lint
        env:
          CI: true
