name: GistMarks CI

on:
  pull_request:
    types: [opened, synchronize, closed]
    branches: ["master"]

jobs:
  lint-and-test-app:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-versions: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: sudo npm install -g yarn
      - run: yarn install --frozen-lockfile
      - run: yarn ci
        env:
          CI: true
